# Generated by Django 4.1.12 on 2023-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("title", models.CharField(max_length=100)),
                (
                    "company",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("location", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "jobs",
            },
        ),
    ]
